// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
window.wailsbindings = {"main":{"App":{"ShowDialog":{"name":"main.App.ShowDialog"}}}};
const go = {
  "main": {
    "App": {
      /**
       * ShowDialog
       * @returns {Promise<void>} 
       */
      "ShowDialog": () => {
        return window.go.main.App.ShowDialog();
      },
    },
  },

};
export default go;
