name: Desktop build
permissions:
  contents: write
# Build for everything on "main" & "v*.*.*"
on:
  repository_dispatch:
    types: [ build ]
  push:
    branches:
      - 'main'
      - 'v*'
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'main'
      - 'v*'
    paths-ignore:
      - '**.md'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      # Install GoLang
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      # Set up GoLang cache
      - name: Go Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      # Install Wails build deps
      - run: sudo apt-get update && sudo apt-get install libgtk-3-0 libwebkit2gtk-4.0-dev
      - run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - run: curl -L -O https://github.com/letheanVPN/lthn-app-desktop/releases/latest/download/lethean-ui.zip && unzip -u lethean-ui.zip -d frontend
      - name: Build
        run: wails build --platform linux/amd64 -webview2 embed
      - run: chmod +x build/bin/lethean
      - name: 'Tar files'
        run: cd build/bin/ && tar -cvf ../../linux-lethean-desktop.tar .
      # uploads the job file, makes no release
      - uses: actions/upload-artifact@v2
        with:
          name: Linux Desktop
          path: linux-lethean-desktop.tar
      # if this is a tag build, upload
      - name: Release Tag
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: linux-lethean-desktop.tar
      - name: Release Branch
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/heads/main')
        with:
          tag_name: canary
          prerelease: true
          files: linux-lethean-desktop.tar
  macos:
    runs-on: macos-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      # Install GoLang
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      # Set up GoLang cache
      - name: Go Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/Library/Caches/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - run: curl -L -O https://github.com/letheanVPN/lthn-app-desktop/releases/latest/download/lethean-ui.zip && unzip -u lethean-ui.zip -d frontend
      - name: Build
        run: wails build --platform darwin/universal -webview2 embed --noPackage
      - run: chmod +x build/bin/lethean.app/Contents/MacOS/lethean
      - name: 'Tar files'
        run: cd build/bin/ && tar -cvf ../../macos-lethean-desktop.tar .
      # uploads the job file, makes no release
      - uses: actions/upload-artifact@v2
        with:
          name: macOS Univesal Desktop
          path: macos-lethean-desktop.tar
      # if this is a tag build, upload
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: macos-lethean-desktop.tar
      - name: Release Branch
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/heads/main')
        with:
          tag_name: canary
          prerelease: true
          files: macos-lethean-desktop.tar
  windows:
    runs-on: windows-2022
    steps:
      # Checkout code
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      # Install GoLang
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      # Set up GoLang cache
      - name: Go Cache
        uses: actions/cache@v2
        with:
          path: |
            %LocalAppData%\go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: curl -L -O https://github.com/letheanVPN/lthn-app-desktop/releases/latest/download/lethean-ui.zip && unzip -u lethean-ui.zip -d frontend
      - run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Build
        run: wails build --platform windows -webview2 embed
      - uses: papeloto/action-zip@v1
        with:
          files: build/bin
          dest: windows-lethean-desktop.zip
      # uploads the job file, makes no release
      - uses: actions/upload-artifact@v2
        with:
          name: Windows Desktop
          path: windows-lethean-desktop.zip
      # if this is a tag build, upload
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: windows-lethean-desktop.zip
      - name: Release Branch
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/heads/main')
        with:
          tag_name: canary
          prerelease: true
          files: windows-lethean-desktop.zip
  lauchers:
    name: "Trigger: letheanVPN/launchers"
    runs-on: ubuntu-latest
    needs:
      - linux
      - windows
      - macos
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: build
          repository: letheanVPN/launchers

