name: Build


on:
  push:
    branches:
      - 'main'
      - 'v*'
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'main'
      - 'v*'
    paths-ignore:
      - '**.md'

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: npm install --legacy-peer-deps
      - run: cd frontend && npm install --legacy-peer-deps
      - name: Install Deno
        run: curl -fsSL https://deno.land/x/install/install.sh | sh && echo "$HOME/.deno/bin" >> $GITHUB_PATH
      - name: Build
        run: wails build --platform darwin/universal
      - uses: actions/upload-artifact@v2
        with:
          name: macos-universal
          path: build/bin/lethean.app
  macos-arm:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: npm install --legacy-peer-deps
      - run: cd frontend && npm install --legacy-peer-deps
      - name: Install Deno
        run: curl -fsSL https://deno.land/x/install/install.sh | sh && echo "$HOME/.deno/bin" >> $GITHUB_PATH
      - name: Build
        run: wails build --platform darwin/arm64
      - uses: actions/upload-artifact@v2
        with:
          name: macos-arm
          path: build/bin/lethean.app
  macos-intel:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: npm install --legacy-peer-deps
      - run: cd frontend && npm install --legacy-peer-deps
      - name: Install Deno
        run: curl -fsSL https://deno.land/x/install/install.sh | sh && echo "$HOME/.deno/bin" >> $GITHUB_PATH
      - name: Build
        run: wails build --platform darwin/amd64
      - uses: actions/upload-artifact@v2
        with:
          name: macos-intel
          path: build/bin/lethean.app
  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: npm install --legacy-peer-deps
      - run: cd frontend && npm install --legacy-peer-deps
      - name: Install Deno
        run: iwr https://deno.land/x/install/install.ps1 -useb | iex
      - name: Build
        run: wails build --platform windows
      - uses: actions/upload-artifact@v2
        with:
          name: windows
          path: build/bin/lethean.exe
