name: Desktop build
permissions:
  contents: write
# Build for everything on "main" & "v*.*.*"
on:
  repository_dispatch:
    types: [ build ]
  push:
    branches:
      - 'main'
      - 'dev'
      - 'v*'
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'main'
      - 'dev'
      - 'v*'
    paths-ignore:
      - '**.md'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2
        with:
          build-name: lethean-linux
          build-platform: linux/amd64
          deno-build: "npm run server:build:linux"
          deno-working-directory: "server"
          wails-build-webview2: "embed"
          wails-version: "v2.3.1"
          go-version: ^1.18
  macos:
    runs-on: macos-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2
        with:
          build-name: lethean
          build-platform: darwin/universal
          deno-build: "npm run server:build:macos-intel"
          deno-working-directory: "server"
          wails-build-webview2: "embed"
          wails-version: "v2.3.1"
          go-version: ^1.18
          sign: "false"
          sign-macos-apple-password: ${{ secrets.APPLE_PASSWORD }}
          sign-macos-app-id: "Developer ID Application: Lethean LTD (W2DNA5L5DY)"
          sign-macos-app-cert: ${{ secrets.MAC_DEVELOPER_CERT }}
          sign-macos-app-cert-password: ${{ secrets.MAC_DEVELOPER_PASS }}
          sign-macos-installer-id: "Developer ID Installer: Lethean LTD (W2DNA5L5DY)"
          sign-macos-installer-cert: ${{ secrets.MAC_DEVELOPER_INSTALL_CERT }}
          sign-macos-installer-cert-password: ${{ secrets.MAC_DEVELOPER_INSTALL_PASS }}

  windows:
    runs-on: windows-2022
    steps:
      # Checkout code
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2
        with:
          build-name: lethean-windows.exe
          build-platform: windows/amd64
          deno-build: "npm run server:build:windows"
          deno-working-directory: "server"
          wails-build-webview2: "embed"
          wails-version: v2.3.1
          go-version: ^1.18


