name: Build
permissions:
  contents: write

on:
  push:
    branches:
      - 'main'
      - 'v*'
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'main'
      - 'v*'
    paths-ignore:
      - '**.md'

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm install --legacy-peer-deps
      - run: cd frontend && npm install --legacy-peer-deps
      - name: Install Deno
        run: curl -fsSL https://deno.land/x/install/install.sh | sh && echo "$HOME/.deno/bin" >> $GITHUB_PATH
      - name: Build
        run: wails build --platform darwin/amd64
      - run: chmod +x build/bin/lethean.app/Contents/MacOS/lethean
      - uses: papeloto/action-zip@v1
        with:
          files: build/bin/lethean.app 
          dest: macos-lethean.app.zip
      - uses: actions/upload-artifact@v2
        with:
          name: macos-lethean.app.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: macos-lethean.app.zip
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm install --legacy-peer-deps
      - run: sudo apt-get install libgtk-3-0 libwebkit2gtk-4.0-dev
      - run: cd frontend && npm install --legacy-peer-deps
      - name: Install Deno
        run: curl -fsSL https://deno.land/x/install/install.sh | sh && echo "$HOME/.deno/bin" >> $GITHUB_PATH
      - name: Build
        run: wails build --platform linux/amd64
      - run: chmod +x build/bin/lethean
      - uses: papeloto/action-zip@v1
        with:
          files: build/bin/lethean
          dest: linux-lethean.zip
      - uses: actions/upload-artifact@v2
        with:
          name: linux-lethean.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: linux-lethean.zip
  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm install --legacy-peer-deps
      - run: cd frontend && npm install --legacy-peer-deps
      - name: Install Deno
        run: iwr https://deno.land/x/install/install.ps1 -useb | iex
      - name: Build
        run: wails build --platform windows
      - uses: papeloto/action-zip@v1
        with:
          files: build/bin/lethean.exe 
          dest: windows-lethean.zip
      - uses: actions/upload-artifact@v2
        with:
          name: windows-lethean.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: windows-lethean.zip
