name: Desktop build
permissions:
  contents: write
# Build for everything on "main" & "v*.*.*"
on:
  repository_dispatch:
    types: [ build ]
  push:
    branches:
      - 'main'
      - 'dev'
      - 'v*'
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'main'
      - 'dev'
      - 'v*'
    paths-ignore:
      - '**.md'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      # Install Wails build deps
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.20.1
      - run: cd server && npm run server:build:linux
      - run: sudo apt-get update && sudo apt-get install libgtk-3-0 libwebkit2gtk-4.0-dev
      - uses: letheanVPN/wails-build-action@main
        with:
          platform: linux/amd64
      - run: chmod +x build/bin/lethean
      - name: 'Tar files'
        run: cd build/bin/ && tar -cvf ../../linux-lethean-desktop.tar .
      # uploads the job file, makes no release
      - uses: actions/upload-artifact@v2
        with:
          name: Linux Desktop
          path: linux-lethean-desktop.tar
      # if this is a tag build, upload
      - name: Release Tag
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: linux-lethean-desktop.tar
      - name: Release Branch
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/heads/main')
        with:
          tag_name: canary
          prerelease: true
          files: linux-lethean-desktop.tar
  macos:
    runs-on: macos-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.20.1
      - run: | 
            brew install mitchellh/gon/gon
            cd server && npm run server:build:macos-intel
      - uses: letheanVPN/wails-build-action@main
        with:
          platform: darwin/universal
      - name: chmod +x exe
        run: chmod +x build/bin/*/Contents/MacOS/*
      - name: Import Code-Signing Certificates for macOS
        if: startsWith(github.ref, 'refs/tags/')
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          keychain-password: ${{ secrets.APPLE_PASSWORD }}
          p12-file-base64: ${{ secrets.MAC_DEVELOPER_CERT }}
          p12-password: ${{ secrets.MAC_DEVELOPER_PASS }}
      - name: Import Code-Signing Certificates for macOS
        if: startsWith(github.ref, 'refs/tags/')
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          keychain-password: ${{ secrets.APPLE_PASSWORD }}
          p12-file-base64: ${{ secrets.MAC_DEVELOPER_INSTALL_CERT }}
          p12-password: ${{ secrets.MAC_DEVELOPER_INSTALL_PASS }}
          create-keychain: false
      - name: Sign our macOS binary
        if: startsWith(github.ref, 'refs/tags/')
        env:
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
        run: |
          echo "Signing Package"
          gon -log-level=info ./build/darwin/gon-sign.json
          echo "Building Zip file"
          ditto -c -k --keepParent ./build/bin/lethean.app ./build/bin/lethean.app.zip
          echo "Building Installer"
          productbuild --sign 'Developer ID Installer: Lethean LTD (W2DNA5L5DY)' --component ./build/bin/lethean.app ./build/bin/lethean.pkg
          echo "notarising Installer and zip"
          gon -log-level=info ./build/darwin/gon-notarize.json
      # uploads the job file, makes no release
      - uses: actions/upload-artifact@v2
        with:
          name: macOS Universal Desktop
          path: build/bin/
      # if this is a tag build, upload
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/bin/lethean.dmg
            build/bin/lethean.pkg
            build/bin/lethean.app.zip

  windows:
    runs-on: windows-2022
    steps:
      # Checkout code
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.20.1
      - run: cd server && npm run server:build:windows
      - uses: letheanVPN/wails-build-action@main
        with:
          platform: windows/amd64
      # uploads the job file, makes no release
      - uses: actions/upload-artifact@v2
        with:
          name: Windows Desktop
          if-no-files-found: error
          path: |
            build\bin\lethean.exe
            build\bin\lethean-amd64-installer.exe
      # if this is a tag build, upload
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build\bin\lethean.exe
            build\bin\lethean-amd64-installer.exe
#
#  lauchers:
#    name: "Trigger: letheanVPN/launchers"
#    runs-on: ubuntu-latest
#    needs:
#      - linux
#      - windows
#      - macos
#    steps:
#      - name: Repository Dispatch
#        uses: peter-evans/repository-dispatch@v2
#        with:
#          token: ${{ secrets.REPO_ACCESS_TOKEN }}
#          event-type: build
#          repository: letheanVPN/launchers
#
