name: Linux
permissions:
  contents: write
# Build for everything on "main" & "v*.*.*"
on:
  push:
    branches:
      - 'main'
      - 'v*'
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'main'
      - 'v*'
    paths-ignore:
      - '**.md'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      # Install / Setup Nodejs v16
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      # Install GoLang
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      # Setup node module caching
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      # Set up GoLang cache
      - name: Go Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      # Helper NPM module install
      - run: npm install --legacy-peer-deps
      # Install Wails build deps
      - run: sudo apt-get update
      - run: sudo apt-get install libgtk-3-0 libwebkit2gtk-4.0-dev
      # Install desktop-angular-app dependencies
      - run: cd frontend && npm install --legacy-peer-deps && npm run build
      # runs deno installer
      - name: Install Deno
        run: curl -fsSL https://deno.land/x/install/install.sh | sh && echo "$HOME/.deno/bin" >> $GITHUB_PATH
      # runs: wails build creating a packaged exe
      - name: Build
        run: wails build --platform linux/amd64
      - run: chmod +x build/bin/lethean
      - name: 'Tar files'
        run: cd build/bin/ && tar -cvf ../../linux-lethean-desktop.tar .
      # uploads the job file, makes no release
      - uses: actions/upload-artifact@v2
        with:
          name: Linux Desktop
          path: linux-lethean-desktop.tar
      # if this is a tag build, upload
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: linux-lethean-desktop.tar
