name: macOS Universal
permissions:
  contents: write

# Build for everything on "main" & "v*.*.*"
on:
  push:
    branches:
      - 'main'
      - 'v*'
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'main'
      - 'v*'
    paths-ignore:
      - '**.md'

jobs:
  macos:
    runs-on: macos-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      # Install GoLang
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      # Set up GoLang cache
      - name: Go Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/Library/Caches/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      # runs: wails build creating a packaged exe
      - name: Build
        run: wails build --platform darwin/universal
      - run: chmod +x build/bin/lethean.app/Contents/MacOS/lethean
      - name: 'Tar files'
        run: cd build/bin/ && tar -cvf ../../macos-lethean-desktop.tar .
      # uploads the job file, makes no release
      - uses: actions/upload-artifact@v2
        with:
          name: macOS Univesal Desktop
          path: macos-lethean-desktop.tar
      # if this is a tag build, upload
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: macos-lethean-desktop.tar
      - name: Release Branch
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/heads/main')
        with:
          tag_name: canary
          prerelease: true
          files: macos-lethean-desktop.tar

