name: MacOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  macos-intel:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: npm install --legacy-peer-deps
      - run: cd frontend && npm install --legacy-peer-deps
      - name: Install Deno
        run: curl -fsSL https://deno.land/x/install/install.sh | sh && echo "$HOME/.deno/bin" >> $GITHUB_PATH
      - name: Build
        run: wails build
