name: Windows
permissions:
  contents: write

# Build for everything on "main" & "v*.*.*"
on:
  push:
    branches:
      - 'main'
      - 'v*'
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'main'
      - 'v*'
    paths-ignore:
      - '**.md'

jobs:
  windows:
    runs-on: windows-2022
    steps:
      # Checkout code
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      # Install GoLang
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      # Set up GoLang cache
      - name: Go Cache
        uses: actions/cache@v2
        with:
          path: |
            %LocalAppData%\go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      # runs: wails build creating a packaged exe
      - run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Build
        run: wails build --platform windows
      - uses: papeloto/action-zip@v1
        with:
          files: build/bin
          dest: windows-lethean-desktop.zip
      # uploads the job file, makes no release
      - uses: actions/upload-artifact@v2
        with:
          name: Windows Desktop
          path: windows-lethean-desktop.zip
      # if this is a tag build, upload
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: windows-lethean-desktop.zip
      - name: Release Branch
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/heads/main')
        with:
          tag_name: canary
          prerelease: true
          files: windows-lethean-desktop.zip
